# Cocoapods

source 'https://github.com/CocoaPods/Specs.git'
# source 'https://gitee.com/rogerabyss/myrepo.git'

platform :ios, '10.0'
use_frameworks!

target 'Strawberry' do

  # 百度 ==========================================
  # 定位
  pod 'BMKLocationKit'
  # ==============================================
  # 支付宝 ==========================================
  pod 'AlipaySDK-iOS'
  # ==============================================
  # 微信 ==========================================
  pod 'WechatOpenSDK'
  # ==============================================
  # 友盟开发者平台 =================================
  # https://developer.umeng.com
  pod 'UMCCommon'
  # 该插件和支付宝冲突
  #  pod 'UMCSecurityPlugins'
  pod 'UMCCommonLog', :configurations => ['Debug','Adhoc','Enterprise']
  # 统计
  pod 'UMCAnalytics'
  # 推送
  # pod 'UMCPush'
  # 分享
   pod 'UMCShare/UI'
   pod 'UMCShare/Social/ReducedWeChat'
   pod 'UMCShare/Social/SMS'
   pod 'UMCShare/Social/Email'
  # 更多请移步: https://developer.umeng.com/docs
  # ==============================================
  
  # 蒲公英平台 =================================
  pod 'Pgyer', :configurations => ['Debug','Adhoc','Enterprise']
  pod 'PgyUpdate', :configurations => ['Debug','Adhoc','Enterprise']
  # 更多请移步: https://www.pgyer.com/doc/view/sdk_ios_guide
  # ==============================================
  
  # 极光开发者平台 ==================================
  # 分享收费
  # pod 'JShare'
  # pod 'JPush'
  # ==============================================
  
  # 图片浏览
  # https://github.com/suzuki-0000/SKPhotoBrowser
  pod 'SKPhotoBrowser'
  # UI框架 =================================
  # 骨架模型
  # https://github.com/Juanpe/SkeletonView
  pod 'SkeletonView', '~> 1.5'
  # 手势
  # FDFullscreenPopGesture
  # https://github.com/forkingdog/FDFullscreenPopGesture
  # navigationController.fd_fullscreenPopGestureRecognizer.enabled = NO;
  # viewController.fd_interactivePopDisabled = YES;
  pod 'FDFullscreenPopGesture', '1.1'
  # Ramotion
  # onboarding
  # https://github.com/Ramotion/paper-onboarding#installation
  # PaperOnboarding
  pod 'paper-onboarding', '~> 6.1.3'
  # button点击效果
  # https://github.com/pmusolino/PMSuperButton
  # 国家选择器
  # https://github.com/949478479/LXCountryCallingCodePicker
  pod 'LXCountryCallingCodePicker'
  pod 'PMSuperButton'
  # Segmentio
  # https://github.com/Yalantis/Segmentio
  # pod 'Segmentio', '~> 3.3'
  # IBAnimatable
  # 这个库可以参考, 本身太重量了
  # https://github.com/IBAnimatable/IBAnimatable
  # pod 'IBAnimatable', '~> 5.2.1'
  # FSPagerView
  # https://github.com/WenchaoD/FSPagerView/
  #  pod 'FSPagerView', '0.8.2'
  # HGCircularSlider
  # https://github.com/HamzaGhazouani/HGCircularSlider
  pod 'HGCircularSlider', '~> 2.1.0'
  # SwiftEntryKit
  # https://github.com/huri000/SwiftEntryKit
  pod 'SwiftEntryKit', '1.0.1'
  # 生物认证
  # https://github.com/rushisangani/BiometricAuthentication
  pod 'BiometricAuthentication'
  # ==============================================
end

target 'AFramework' do
  inherit! :search_paths

  # 网络层框架 Carthage老出问题, Pods稳定, 快速
  # Moya ==========================================
  # Alamofire
  # Result
  # RxSwift
  # https://github.com/Moya/Moya
  pod 'Moya', '13.0.0'
  pod 'Moya/RxSwift', '13.0.0'
  pod 'RxSwift', '4.5.0'
  pod 'RxCocoa', '4.5.0'
  # ===============================================

  # 测试助手 =====================================================
  # https://github.com/didi/DoraemonKit
  pod 'DoraemonKit/Core', '~> 1.2.0', :configurations => ['Debug','Adhoc','Enterprise']
  pod 'DoraemonKit/WithLogger', '~> 1.2.0', :configurations => ['Debug','Adhoc','Enterprise']
  pod 'DoraemonKit/WithGPS', '~> 1.2.0', :configurations => ['Debug','Adhoc','Enterprise']
  pod 'DoraemonKit/WithLoad', '~> 1.2.0', :configurations => ['Debug','Adhoc','Enterprise']
  # ==============================================================
  
  # 稳定中
  # reachable
  # https://github.com/ashleymills/Reachability.swift
  pod 'ReachabilitySwift', '4.3.1'
  # EmptyDataSet
  # https://github.com/Xiaoye220/EmptyDataSet-Swift
  pod 'EmptyDataSet-Swift', '~> 4.2.0'
  # YPImagePicker
  # https://github.com/Yummypets/YPImagePicker
  pod 'YPImagePicker'
  # PopupDialog
  # https://github.com/Orderella/PopupDialog
  pod 'PopupDialog', '~> 0.9.2'
  # Sheeeeeeeeet
  # https://github.com/danielsaidi/Sheeeeeeeeet
  pod 'Sheeeeeeeeet', '~> 2.0.0'
  # PGDatePicker
  # https://github.com/xiaozhuxiong121/PGDatePicker
  pod 'PGDatePicker', '~> 2.6.9'
  # ObjectMapper
  # https://github.com/tristanhimmelman/ObjectMapper
  # 地址选择器 用到了这个鬼东西
  pod 'ObjectMapper'
  # DropDown
  # https://github.com/AssistoLab/DropDown
  pod 'DropDown', '2.3.12'
  
  # 测试中

  # SwiftyRSA
  # https://github.com/TakeScoop/SwiftyRSA
  #  pod 'SwiftyRSA'

  target 'AFramework-Tests' do
    inherit! :search_paths
  end
end
